version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskflow-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "YourPassword123!"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - taskflow-network

networks:
  taskflow-network:
    driver: bridge

volumes:
  sqlserver_data: